# Generated by Django 5.0.7 on 2024-09-03 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="day_grade",
            name="student_grade",
            field=models.ManyToManyField(
                blank=True, related_name="day_grade", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
