# Generated by Django 5.0.7 on 2024-09-02 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolclass",
            name="classes",
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="students",
            field=models.ManyToManyField(
                related_name="school_classes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="duration",
            field=models.DurationField(verbose_name="Тривалість"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="lessons", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="bases.teacher",
            ),
        ),
    ]
