# Generated by Django 5.0.7 on 2024-09-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bases", "0002_remove_schoolclass_classes_schoolclass_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="duration",
            field=models.TimeField(verbose_name="Тривалість"),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="students",
            field=models.ManyToManyField(
                related_name="school_classes", to="auth.group"
            ),
        ),
    ]
