# Generated by Django 5.0.7 on 2024-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bases", "0003_alter_lesson_duration_alter_schoolclass_students"),
    ]

    operations = [

        migrations.AlterField(
            model_name="lesson",
            name="finish",
            field=models.TimeField(verbose_name="Кінець"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="start",
            field=models.TimeField(verbose_name="Початок"),
        ),
    ]
