# Generated by Django 5.0.7 on 2024-09-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bases", "0004_lesson_date_alter_lesson_finish_alter_lesson_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="finish",
            field=models.DateTimeField(verbose_name="Кінець"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="start",
            field=models.DateTimeField(verbose_name="Початок"),
        ),
    ]
