# Generated by Django 5.0.7 on 2024-09-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bases", "0005_alter_lesson_finish_alter_lesson_start"),
    ]

    operations = [

    ]
