# Generated by Django 5.0.7 on 2024-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bases", "0007_remove_lesson_dates"),
    ]

    operations = [

    ]
